export const MATERIAL_CODE = 'MATERIAL_CODE';
export const MATERIAL_NAME = 'MATERIAL_NAME';

// Assignment
export const ASSIGNMENT = {
  LIST_BY_MABES_ON_REQ: 'ASSIGNMENT_LIST_BY_MABES_ON_REQ',
  LIST_BY_MANDOR_ON_REQ: 'ASSIGNMENT_LIST_BY_MANDOR_ON_REQ',
  LIST_BY_MABES_ON_FINISH: 'ASSIGNMENT_LIST_BY_MABES_ON_FINISH',
  LIST_BY_MANDOR_ON_FINISH: 'ASSIGNMENT_LIST_BY_MANDOR_ON_FINISH',
};

export const UPDATE_SESSION = 'UPDATE_SESSION';
export const TOAST = {
  SHOW: 'SHOW_TOAST',
  HIDE: 'HIDE_TOAST',
};
